sudo: false
language: python
python: 3.6
install:
  - pip install -r requirements.txt
  - pip install codecov pytest pytest-cov
env:
  - TESTRAIL_GROUP=openstax
  - SHOW_ALL_RESULTS=false
  - NON_PLAN_ID=999
  - TESTRAIL_USER="no_user_testing"
  - TESTRAIL_VALUE=""
script: python -m pytest -v --cov=./
after_success:
  - codecov
